[general]

import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"
decorations = "None"

opacity = 0.95
blur = true
# blur = false

option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 11.5

# general.import = [
#   # uncomment the flavour you want below:
#   # "~/.config/alacritty/catppuccin-latte.toml"
#   # "~/.config/alacritty/catppuccin-frappe.toml"
#   # "~/.config/alacritty/catppuccin-macchiato.toml"
#   "~/.config/alacritty/catppuccin-mocha.toml"
# ]
